# Connection details for the OpAMP server.
server:
    endpoint: wss://localhost:1729
    #    tls:
    # Client-side TLS configuration to connect to the OpAMP server.

agent:
    # Describes the configuration properties of the agent.
    config:
        # Currently, only a `file' based configuration is accepted.
        file: /opt/opentelemetry-collector/config.yaml
        # If `auto_reload` is true, then the agent doesn't need a restart on a config
        # change as it is internally managed by the agent.
        auto_reload: false

    # TODO: another way of specifying configuration that allows configuration
    # to be fetched and updated via network call.
    config_alt:
        read:
            # source: file:/opt/opentelemetry-collector/config.yaml
            source: http://localhost:1010/config # GET
            content_type: application/yaml
        write:
            # dest: file:/opt/opentelemetry-collector/config.yaml
            dest: http://localhost:1010/config # PUT
            content_type: application/yaml
        auto_reload: false

    # Dictates how to check if the agent is healthy.
    health_check:
        url: http://localhost:13133/
        initial_delay: 5s
        period: 5s
        timeout: 20s

    # An arbitrary set of key-value pairs that identify this agent and may
    # describe where this agent runs.
    attrs:
        -   service.name: io.opentelemetry.collector
        -   service.namespace: collector
        -   other_attr1: other_attr1_val
        -   other_attr2: other_attr2_val

    command:
        # systemd:
        #     name: ot-collector
        exec:
            name: /opt/opentelemetry-collector/bin/otel
            # Set of command-line arguments required to start the `executable` specified
            # above.
            args:
                - --config
                - /etc/otel/config.yaml

# Watchdog allows the supervisor to monitor the health of the agent and ensure
# it is always running (restarting if necessary). In this sense, it acts as
# an alternative to agent installations that are not managed by systemd.
#
# A watchdog policy, like `systemd', albeit not as exhaustive, allows the
# watchdog to honor certain timing restrictions during the start, stop and
# restart of the agents.
watchdog:
    # Max attempts the agent is allowed to fail when attempted to START or
    # STOP in which case the operation will be re-attempted.
    max_attempts: 3
    # Duration to wait between successive attempts of a START or STOP.
    wait_between_attempts: 1s
